INSERT INTO area_servicio (id, nombre) VALUES
(1, 'Energía asequible y no contaminante'),
(2, 'Agua limpia y saneamiento'),
(3, 'Acción por el clima'),
(4, 'Cultural'),
(5, 'Diversidad cultural'),
(6, 'Trabajo decente y crecimiento económico'),
(7, 'Diversidad'),
(8, 'Igualdad de género'),
(9, 'Salud y bienestar'),
(10, 'Preservación histórica/cultural'),
(11, 'Industria'),
(12, 'Industria, innovación e infraestructura'),
(13, 'Innovación e infraestructura'),
(14, 'Paz, justicia e instituciones sólidas'),
(15, 'Vida submarina'),
(16, 'Vida de ecosistemas terrestres'),
(17, 'Fin de la pobreza'),
(18, 'Alianzas para lograr los objetivos'),
(19, 'Paz'),
(20, 'Paz, justicia e instituciones sólidas'),
(21, 'Educación de calidad'),
(22, 'Reducción de las desigualdades'),
(23, 'Producción y consumo responsables'),
(24, 'Justicia social'),
(25, 'Ciudades y comunidades sostenibles'),
(26, 'Hambre cero');


INSERT INTO area_conocimiento (id, nombre) VALUES
(1, 'Teoría del Actor-Red'),
(2, 'Ciencias Administrativas'),
(3, 'Ciencias Agógicas'),
(4, 'Antropología'),
(5, 'Arqueología'),
(6, 'Arte para la Biodiversidad'),
(7, 'Artes'),
(8, 'Contexto Audiovisual'),
(9, 'Trastorno del Espectro Autista'),
(10, 'Alfabetización Bilingüe'),
(11, 'Biología'),
(12, 'Administración de Empresas'),
(13, 'Comunicación Empresarial'),
(14, 'Química'),
(15, 'Clínica'),
(16, 'Comunicación'),
(17, 'Ciencias de la Comunicación, Marketing y Medios Digitales'),
(18, 'Ciencias de la Computación'),
(19, 'Psicología Histórico-Cultural'),
(20, 'Inteligencia Cultural'),
(21, 'Estudios Culturales'),
(22, 'Cultura Democrática'),
(23, 'Odontología'),
(24, 'Desarrollo'),
(25, 'Didáctica'),
(26, 'Didáctica y Pedagogía Especial'),
(27, 'Tecnologías Digitales'),
(28, 'Tecnologías Digitales en Educación'),
(29, 'Educación a Distancia'),
(30, 'Diversidad Funcional y Cognitiva'),
(31, 'Ciencias de la Tierra'),
(32, 'Economía'),
(33, 'Economía y Negocios'),
(34, 'Educación'),
(35, 'Políticas Educativas'),
(36, 'Educación, Aprendizaje-Servicio'),
(37, 'Educación, Aprendizaje-Servicio, Investigación'),
(38, 'Aprendizaje Emocional'),
(39, 'Aprendizaje Participativo'),
(40, 'Ingeniería y Tecnología'),
(41, 'Evaluación'),
(42, 'Lengua Extranjera'),
(43, 'Fundamentos de la Protección Social y Legal'),
(44, 'General'),
(45, 'Geografía'),
(46, 'Geociencias'),
(47, 'Gerontología'),
(48, 'Historia'),
(49, 'Geografía Humana'),
(50, 'TIC (Tecnologías de la Información y Comunicación)'),
(51, 'Ciencias de la Información y Comunicación'),
(52, 'Ciencias de la Información, Educación'),
(53, 'Innovación'),
(54, 'Política Lingüística'),
(55, 'Idiomas y Literatura'),
(56, 'Derecho'),
(57, 'Gestión'),
(58, 'Marketing y Publicidad'),
(59, 'Matemáticas'),
(60, 'Medicina'),
(61, 'Medicina y Salud'),
(62, 'Medicina y Enfermería'),
(63, 'Mentoría'),
(64, 'Metodología'),
(65, 'Estudios sobre Migración'),
(66, 'Microbiología'),
(67, 'Educación Musical'),
(68, 'Enfermería'),
(69, 'Educación en Terapia Ocupacional'),
(70, 'Aprendizaje en Línea'),
(71, 'Abierto a Diferentes Disciplinas'),
(72, 'Otros'),
(73, 'Pastoral'),
(74, 'Pedagogía y Didáctica'),
(75, 'Pedagogía'),
(76, 'Pedagogía y Económicas'),
(77, 'Pedagogía en la Sociología'),
(78, 'Artes Escénicas'),
(79, 'Educación Física'),
(80, 'Educación Física y Deporte'),
(81, 'Física'),
(82, 'Fisioterapia'),
(83, 'Plástica'),
(84, 'Ciencia Política'),
(85, 'Enseñanza en Educación Primaria'),
(86, 'Psicología'),
(87, 'Salud Pública'),
(88, 'Gestión Pública'),
(89, 'Evaluación de la Calidad'),
(90, 'Investigación e Intervención en Educación'),
(91, 'Usuarios de Investigación'),
(92, 'Desarrollo Rural'),
(93, 'Economía Social'),
(94, 'Educación Social'),
(95, 'Justicia Social'),
(96, 'Ciencias Sociales'),
(97, 'Trabajo Social'),
(98, 'Educación en Trabajo Social'),
(99, 'Sociología'),
(100, 'Ciencias del Espacio'),
(101, 'Necesidades Especiales'),
(102, 'Estadísticas'),
(103, 'Desarrollo Sostenible'),
(104, 'Teología'),
(105, 'Tercer Sector'),
(106, 'Competencias Transversales'),
(107, 'Planificación Urbana'),
(108, 'Urbanismo y Arquitectura'),
(109, 'Movilidad Virtual'),
(110, 'Política de Juventud');

